### ISSUE TITLE
popper-toggle-latest cycles through popup buffers before closing

### ISSUE THREAD

**Issue by daviwil** [karthink/popper#13]
**Repro Steps**

1. Use the configuration below (maybe tweak the bindings)
2. Launch `eshell`, popper catches it correctly
3. Use `describe-function` on `popper-mode`, popper catches it correctly
4. Run `popper-toggle-latest` twice; the first press will cycle to the `eshell` buffer and the second press will close the popup window
5. Subsequent runs of `popper-toggle-latest` will open and close the popup window correctly

**Configuration**

```lisp
(use-package popper
  :ensure t
  :bind (("C-M-'" . popper-toggle-latest)
         ("M-'" . popper-cycle)
         ("C-M-\"" . popper-toggle-type))
  :custom
  (popper-reference-buffers
   '("^\\*eshell\\*"
     help-mode))
  :init
  (popper-mode 1))
```

**Comment by karthink** [comment]
Second bug. Reproduce by:

- `describe-function` on `popper-mode`
- M-x `eshell`: eshell replaces the help window
- Call `popper-toggle-latest`: eshell goes away
- Call `popper-toggle-latest` again: eshell should show up, the help window shows up instead.

**Comment by daviwil** [comment]
Both fixed, thanks a bunch!
