### ISSUE TITLE
[feature request] buffer count when cycling

### ISSUE THREAD

**Issue by m160** [karthink/popper#14]
It'd be nice see how many popper buffers there are and at which one you're currently at when popper-cycling.
Something like [1/4], [2/4], [3/4], [4/4] as you cycle through them.

**Comment by karthink** [comment]
Here's a cleaner version with some decorators for longer buffer names:

https://user-images.githubusercontent.com/8607532/135590385-2bf212ad-4d32-448b-8602-a3657125ce5e.mp4

**Comment by karthink** [comment]
If you want to test it out, you can checkout the [echo-area-notify](https://github.com/karthink/popper/tree/echo-area-notify) branch. To enable the messaging, use

```elisp
(add-hook 'popper-open-popup-hook 'popper-echo-names)
```

That should get you the behavior in the first video.

If you want to transform the names that appear in some way, you can customize `popper-message-transform-function`. Here is the chicken scratch function I'm using for now:

```elisp
(setq popper-message-transform-function #'popper-message-shorten)

(defun popper-message-shorten (name)
  (cond
   ((string-match "^\\*[hH]elpful.*?: \\(.*\\)\\*$" name)
    (concat (propertize "[H]" 'face '(:foreground "DarkOliveGreen4"))
            (match-string 1 name)))
   ((string-match "^\\*Help:?\\(.*\\)\\*$" name)
    (concat (propertize "[H]" 'face '(:foreground "DarkOliveGreen4"))
            (match-string 1 name)))
   ((string-match "^\\*eshell:? ?\\(.*\\)\\*$" name)
    (concat (propertize "[E]" 'face '(:foreground "blue"))
            (match-string 1 name)))
   ((string-match "^\\*\\(.*?\\)\\(?:Output\\|Command\\)\\*$" name)
    (concat (propertize "[O]" 'face '(:foreground "IndianRed"))
            (match-string 1 name)))
   ((string-match "^\\*\\(.*?\\)[ -][Ll]og\\*$" name)
    (concat (propertize "[L]" 'face '(:foreground "DarkGoldenrod4"))
            (match-string 1 name)))
   ((string-match "^\\*[Cc]ompil\\(?:e\\|ation\\)\\(.*\\)\\*$" name)
    (concat (propertize "[C]" 'face '(:foreground "IndianRed"))
            (match-string 1 name)))
   (t name)))
```

**Comment by m160** [comment]
That was fast, very nice!

**Comment by karthink** [comment]
This is basically done. See the revamped Readme (many new demos) for details. Short version: Turn on `popper-echo-mode` and you're set.

I'm closing this issue, but I understand that you wanted numbers like [1/4], not the superset that was actually implemented. If you still want the numbers feel free to reopen the issue!

**Comment by m160** [comment]
Numbers is nice if you a bunch of popper buffers, but this is even better when you only have a few. It'd be nice with both, but I'd say this implementation will suffice 95% of the time for me. Tried it out now with no issues, nice work!

**Comment by karthink** [comment]
If you have more than 10 popup buffers (per group) and the one you need is 8 buffers away in the list neither the echo-area list nor seeing [1/10] seem helpful, your best bet is to just call `switch-to-buffer` or `display-buffer`. Popper's goal is to ensure the buffer you want is never more than 2-3 `popper-cycle` calls away (and usually just available through `popper-toggle-latest`), for which the echo area list works well.

I must admit I don't quite understand the use of seeing something like [5/13].

**Comment by m160** [comment]
Just as orientation to see how many buffers there are and where you are when cycling through them, not a big deal.
