### ISSUE TITLE
ignore wrong number in popper-echo

### ISSUE THREAD

**Issue by tshu-w** [karthink/popper#16]
Hi, I sometimes press the wrong number (larger than the current popper buffer number), and I got `(wrong-type-argument stringp nil)` and popper quit.
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  display-buffer(nil)
  #f(compiled-function (&optional arg) (interactive "P") #<bytecode -0x18e4d8fa6e778aff>)(nil)
  funcall-interactively(#f(compiled-function (&optional arg) (interactive "P") #<bytecode -0x18e4d8fa6e778aff>) nil)
  command-execute(#f(compiled-function (&optional arg) (interactive "P") #<bytecode -0x18e4d8fa6e778aff>))
```
It would be nice to catch out-of-range arg and tell the user, but don't quit popper buffers

**Comment by karthink** [comment]
Done.

Note: Popper can't inform the user because the echo-area is being used to show the popup list. Keys that are not mapped to popups no do nothing.
