### ISSUE TITLE
Not support config `quickrun--mode` 

### ISSUE THREAD

**Issue by zw963** [karthink/popper#23]
When i set like this, it not work.

```el
(setq popper-reference-buffers
      '(
        quickrun--mode
        ))
```

---------------

though,  after change like this, it works

```cl
(setq popper-reference-buffers
      '(
              "\\*quickrun\\*"
        ))
```

please check this mode here. 

https://github.com/emacsorphanage/quickrun

**Comment by karthink** [comment]
This depends on whether the mode is set before or after the buffer display. If it's set after, like with `quickrun--pop-to-buffer`, there's nothing Popper can do to capture it by mode. This is also an issue with shells, see #2. Identifying popups by name is more reliable, but there are exceptions here too. Unfortunately there is no unified solution to this except for including both the name and mode in `popper-reference-buffers`.
