### ISSUE TITLE
popper controlled buffer only be suppressed the first time buffer is open, than, never hiden it when active this window use one command

### ISSUE THREAD

**Issue by zw963** [karthink/popper#24]
I use [hover.el](https://github.com/ericdallo/hover.el) for flutter development.

i guess it use [this](https://github.com/ericdallo/hover.el/blob/master/hover.el#L269) pop-to-buffer-same-window to use compilation-start function to start a process in a buffer.

following is my settings:

```cl
(require 'popper)
(require 'popper-echo)

;; 注意，有一些模式使用 mode-name 方式是无法生效的.
(setq popper-reference-buffers
      '("\\*Messages\\*$"
        "Output\\*$"
        ;; "LSP Error List\\*$"
        "\\*Async Shell Command\\*"
        "\\*quickrun\\*$"
        ;; "Scratch.txt"
        vterm-mode
        inf-ruby-mode
        (special-mode . hide)
        ("\\*Hover\\*" . hide)
        (hover-mode . hide)
        (compilation-mode . hide)
        help-mode
        ))

;; (defun popper-select-popup-at-top (buffer &optional _alist)
;;   "Display popup-buffer BUFFER at the bottom of the screen."
;;   (let ((win (display-buffer-in-side-window
;;               buffer
;;               `((window-height . ,popper-window-height)
;;                 (side . top)
;;                 (slot . 1)))))
;;     (select-window win)))
;; (setq popper-display-function #'popper-select-popup-at-top)

(global-set-key [(shift control t)] 'popper-toggle-latest)
(with-eval-after-load 'vterm
  (define-key vterm-mode-map [(shift control t)] 'popper-toggle-latest))
(global-set-key (kbd "C-`") 'popper-cycle)
(global-set-key (kbd "C-M-`") 'popper-toggle-type)
(popper-mode +1)
(popper-echo-mode +1)
(setq popper-window-height 50)
```

It works when i first run `hover-run-or-hot-reload`, it works, i can see some info tips on minibuffer: `Popup suppressed: *Hover*`
but, after it was start the first time, hidden feature never works, it always popup after i run above command, and quite annoy.

i can saw the pop window mode line like this:

![image](https://user-images.githubusercontent.com/549126/149944552-3d519e94-b209-40e2-a28c-26f1fdd4457b.png)

I add both major-mode name `hover-mode` and buffer name `*Hover*` into popper-reference-buffers, but both all not work.

thank you.

**Comment by zw963** [comment]
Okay, i saw the readme section about this now.

https://github.com/karthink/popper#suppressing-popups

> Popper can suppress popups when they are first created

so,  there is no way can always suppress one buffer to avoid interrupt, right?

**Comment by zw963** [comment]
I guess i am misunderstood somethings, i have to research shackle to resolve this issue, it seem like works.

anyway, this not a problem for me.

for the hidden keyword, if that only hidden window the first time, i consider this not so useful, if this is the expected behavior, please close it, it fine for me to use shackle handle it.

Thank you.

**Comment by karthink** [comment]
This feature is intended to suppress newly spawned buffers from disturbing your window layout.

To always suppress one buffer, you can do something like this:
```
(setq popper-display-function
      (defun popper-select-popup-at-bottom-maybe-hide (buffer &optional _act)
        (if (popper--suppress-p buf)
            (display-buffer-no-window buf '((allow-no-window . t)))
          (popper-select-popup-at-bottom buf _act))))
```

**Comment by zw963** [comment]
i am suppress some window use shackle for now, i will try it later, thank you very much.
