### ISSUE TITLE
request to have an option to not change mode-line-format

### ISSUE THREAD

**Issue by cburroughs** [karthink/popper#25]
Setting `popper-mode-line` to nil causes popper to display no modeline.  Instead I'd like to instead have popper not change the mode-line at all.  I'd like to be able to see all of the normal helpful things in the mode-line (name, mode, etc) while also being able to treat it as a "popup".

**Comment by karthink** [comment]
> Instead I'd like to instead have popper not change the mode-line at all.

`(setq popper-mode-line "")`

**Comment by cburroughs** [comment]
Thank you!

**Comment by karthink** [comment]
@cburroughs cheers
