### ISSUE TITLE
Popper replaces simple-modeline

### ISSUE THREAD

**Issue by TrunovS** [karthink/popper#26]
Hello)

Thanks for great package! 

Right now im using package  *simple-modeline* ```(use-package simple-modeline``` and discovered some strange behavior. When popper enabled and some buffer marked  as "POP" (for example *scratch*) frame modeline replaced with popper-mode-line:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/13647806/151034675-b0a265c8-7bb6-46f6-9605-03fb03c3c367.png">

At the same time with default emacs modeline popper just append "POP" at the beginning:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/13647806/151035081-1ee1dc56-252b-4b0a-b6c7-be6a4ea500ea.png">

Is there some way to append "POP" for simple-mode line too? Just append, not replace?

**Comment by karthink** [comment]
Fixed in a50edec, please test.

**Comment by TrunovS** [comment]
Works like a charm! Thanks a lot!
