### ISSUE TITLE
Cycling and toggling with buffers which display full frame

### ISSUE THREAD

**Issue by clemera** [karthink/popper#3]
Thanks for this nice package,

with `(setq popper-display-control nil)` and a popup buffer which displays full frame the cycling and toggling doesn't work. To reproduce you can use a single window frame using the following display action for example:

```elisp
(add-to-list 'display-buffer-alist
             `(,(rx bos "*Messages*" eos)
               (display-buffer-same-window)))
```

**Comment by karthink** [comment]
This is the result of making design decisions centered on my personal workflow 🤦. I didn't imagine someone would want to use popups fullscreen. I'll fix it soon.

Out of curiosity, is this how you intend to use this package or are you just exploring?

**Comment by clemera** [comment]
I would be crazy enough to use it like that :laughing: but only if you think it fits well enough in your design/scope for the package. My window management is probably a bit uncommon, I'm usually on a small screen and default to full screen display with some side windows for special cases.

**Comment by karthink** [comment]
Should be fixed in 35e266d9. Please test (esp. popup cycling for funky behavior).

> if you think it fits well enough in your intended design/scope for the package.

I want for the popup logic to be completely separate from the buffer display logic, so it's well within scope. I actually didn't want to bother with any buffer display logic at all (so that `popup-display-control` is always `nil` and not needed) since `display-buffer-alist` is well documented and there are many packages that do a great job of modifying it, but popper is very hard to explain to most users without some basic display behavior included.

**Comment by clemera** [comment]
Cycling seems to work now, one thing I noticed with toggling is that if you have multiple windows and toggle to a full window popup buffer and afterwards toggle back the initial window arrangement is gone and you have the initially selected window now covering the full frame.

Your approach makes a lot of sense to me, it integrates nicely with existing setups and also for people which don't have any, great work!

**Comment by karthink** [comment]
> One thing I noticed with toggling now is that if you have multiple windows and toggle to a full window popup buffer and afterwards toggle back the initial window arrangement is gone and you have the initially selected window now covering the full frame.

Yeah, this is tricky to fix without implementing a half-baked version of `winner-mode` inside Popper. For now I'm thinking of providing some hooks so you can save/restore the window configuration before/after dismissing a full screen popup.

**Comment by clemera** [comment]
> Yeah, this is tricky to fix without implementing a half-baked version of winner-mode inside Popper. For now I'm thinking of providing some hooks so you can save/restore the window configuration before/after dismissing a full screen popup.

Maybe leave it like it is I realize what I'm looking for is a bit different,  I'm more interested in the buffers than the windows (I use full frame windows most of the time). I'm probably better off using a buffer categorization package and then cycle through those category buffers within the same window. Anyway thanks for your help and the quick fix, cycling seems to also work nicely with full frame windows now!
