### ISSUE TITLE
Flickering issue while fit-window-to-buffer

### ISSUE THREAD

**Issue by seagle0128** [karthink/popper#31]
I am enjoying this great extension. Thanks again!

Only one minor issue troubles me. While the popper window popups, the flickering will be observed. I went through the codes of shackle, the mechanism is totally different. So far I don't have any idea to address it. Not sure if you have the same issue, and have any solution. Please take a look.

**Comment by karthink** [comment]
@seagle0128 I'm unable to reproduce the flicker. 

> I went through the codes of shackle, the mechanism is totally different. So far I don't have any idea to address it.

Popper calls display-buffer with a custom display-buffer function, it's not doing anything fancy. 

Does the flickering happen when you call `fit-window-to-buffer` interactively?

**Comment by karthink** [comment]
Also, does the flicker disappear if you use a different `popper-display-function`, for example:

```lisp
(defun popper-select-popup-at-bottom (buffer &optional _alist)
  "Display and switch to popup-buffer BUFFER at the bottom of the screen."
  (let ((window (display-buffer-in-side-window
   buffer
   `((window-height . 14)
     (side . bottom)
     (slot . 1)))))
    (select-window window)))

(setq popper-display-function #'popper-select-popup-at-bottom)
```

**Comment by seagle0128** [comment]
There is no flickering with the snippet above. If the `window-height` is fixed, no flickering. I think `fit-window-to-buffer` cause the issue.

**Comment by karthink** [comment]
To be clear, there is no flickering when you call `fit-window-to-buffer` interactively?

**Comment by seagle0128** [comment]
Right.
- No issue while calling `fit-window-to-buffer` interactively.
- No issue if the `window-height` is fixed.

**Comment by seagle0128** [comment]
I got the recording today. FYI

[Screen Recording 2022-03-23 at 14.52.06.zip](https://github.com/karthink/popper/files/8330478/Screen.Recording.2022-03-23.at.14.52.06.zip)

**Comment by karthink** [comment]
I noticed you have doom-modeline active. On a hunch I installed doom-modeline and I can reproduce the flickering now. 

Could you check if the flickering persists without doom-modeline active?

**Comment by karthink** [comment]
Doom-modeline is forcing a redisplay when running `fit-window-to-buffer`, see `doom-modeline-redisplay`. You can fix this issue by running 

```lisp
(advice-remove #'fit-window-to-buffer #'doom-modeline-redisplay)
```

after activating `doom-modeline`. Depending on the height of your doom-modeline, this might make the calculated window height slightly incorrect, but it seems to work fine for me.

**Comment by seagle0128** [comment]
Oh, I forgot this workaround in `doom-modeline`, although I am the author. Apologies! I am closing it.
