### ISSUE TITLE
How to turn consult ripgrep as buffer, and what font do you use?

### ISSUE THREAD

**Issue by Mariownyou** [karthink/popper#39]

**Comment by karthink** [comment]
The typical way to turn consult-ripgrep to a grep buffer is to call embark-export. You'll need the embark-consult package to be installed.

I'm not sure what font you're referring to. Typically some variant of Iosevka for fixed-pitch.

Did you have an issue regarding Popper?

**Comment by kenranunderscore** [comment]
@Mariownyou You probably mean the font used in the screencasts in the README file. Very sure that this is Fantasque Sans Mono.
