### ISSUE TITLE
Pressing Ctrl-` to open or close POP buffer causes backtick to get entered repeatedly

### ISSUE THREAD

**Issue by RKBK** [karthink/popper#4]
Thanks for this interesting contribution to window management in emacs!

Intermittently after using the popper command `popper-toggle-latest` (or `popper-cycle`) through my keybind C-`, the ` key gets "stuck" and just keeps getting entered into the current active buffer (`````````````` until I stop it) after turning on or off popper. I have to press C-g to quit to stop it, or press another key.

I'm using emacs under WSL in Windows 10 with the vcxsrv X server.

**Comment by karthink** [comment]
If I understand this correctly, sometimes when you press ``C-` ``  a popup opens/closes and then a stream of backticks are entered into your active buffer? I'm having trouble thinking of what code in Popper could be causing this, since it doesn't handle keyboard input in any way. Does this happen if you press  `` ` `` or ``C-` `` when (i) `popper-mode` is off, or (ii) when it's not bound to `popper-toggle-latest` or `popper-cycle`?

**Comment by RKBK** [comment]
It's almost like the buffer opening and closing action gets somehow out of sync with the key press, because the open/close is slow (running under WSL?). 

I also tried popper right now on a linux laptop, and here I cannot reproduce the same behaviour.

**Comment by RKBK** [comment]
When it happens, I get the following in messages:
```
No buried popups [2 times]
` is undefined [23 times]
```
(i.e. `` is undefined` for every time it gets triggered in the undesired way)

**Comment by karthink** [comment]
I haven't been able to reproduce this on Linux either. I don't have access to WSL so I can't test there. I want to understand if this is an issue with the grave (``` ` ```) key specifically, can you test this by binding `popper-toggle-latest` to a different key?

**Comment by RKBK** [comment]
Today, I have tried to get it to reappear on the same computer I originally saw it. However, I didn't see it again. I'll close this issue, since it might not have anything to do with Popper anyway. If I manage to repeat it, I'll try with a different key bind and see what happens then.
