### ISSUE TITLE
After using corfu in a popup, popper-toggle-latest does not hide popper window

### ISSUE THREAD

**Issue by fredericgiquel** [karthink/popper#41]
# Summary

After using `corfu` in a popup, `popper-toggle-latest` does not hide `popper` window.

# Steps to reproduce

With the following `init.el` file:

```emacs-lisp
;; Initialize package sources
(require 'package)

(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("nongnu" . "https://elpa.nongnu.org/nongnu/")
                         ("melpa" . "https://melpa.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)

(use-package corfu
  :init
  (global-corfu-mode))

(use-package popper
  :bind ("C-`" . popper-toggle-latest)
  :init
  (setq popper-reference-buffers
        '("^\\*ielm\\*$" inferior-emacs-lisp-mode))
  (popper-mode +1)
  (popper-echo-mode +1))
```

- Use "M-x ielm" to open an Emacs lisp REPL in a popup window
- Enter "popper-open-popup-alist" (without using completion) in IELM prompt
- The evaluation of this variable should return an alist containing IELM buffer
- Use "C-`" to check that popup window is hidden as expected
- Use "C-`" a second time to reuse IELM
- Enter "popper-open-popup-alist" using "TAB" somewhere in the middle to trigger `corfu` completion
- The evaluation of this variable should now return `nil`
- Use "C-`" to hide popper window

The last command does not work as expected.

# Possible workaround

`corfu` uses child-frame to display completion candidates. So I tried to add following lines in init file.

```emacs-lisp
(advice-add #'popper--update-popups :before-until #'frame-parent)
(advice-add #'popper--suppress-popups :before-until #'frame-parent)
```

It prevents `popper-open-popup-alist` from being changed from a child-frame and seems to fix the problem without side effects.
But I have not tested enough to be sure.

**Comment by fredericgiquel** [comment]
Fixed by https://github.com/karthink/popper/commit/50568b8af2ee4c43d4a5b55241fac7ef11e2f9db :+1: 

I think we can close this issue.

**Comment by karthink** [comment]
Thanks for the detailed bug report @fredericgiquel!
