### ISSUE TITLE
Unexpected behavior when defining custom display rules

### ISSUE THREAD

**Issue by JosephFerano** [karthink/popper#42]
Hello, thank you again for this great package. I am trying to define some custom rules for popper which goes like this;

- If a popper popup already exists, just re-use that
- If there are no windows, split right
- If there are windows/splits and none are popper popups, split below the current window

Things work more or less as expected, however, I haven't been able to get the first rule working. In the code I present below, the first condition of the `cond` expression checks to see if `popper-popup-status` is non-nil, then moves to other windows to check to see if any of them have this status. This is returning nil when called from popper. However, if I eval the `(or popper-popup-status...)` condition with `M-:`, it returns "popup" so it seems to be working when evaluated like that. Here is the code I have so far, it is still WIP:

```lisp
(defun joe/popper-display-func (buffer &optional _alist)
  (cond
   ((or popper-popup-status
        (when (window-in-direction 'above) (save-selected-window (windmove-up) popper-popup-status))
        (when (window-in-direction 'right) (save-selected-window (windmove-right) popper-popup-status))
        (when (window-in-direction 'below) (save-selected-window (windmove-down) popper-popup-status))
        (when (window-in-direction 'left) (save-selected-window (windmove-left) popper-popup-status)))
    (display-buffer-reuse-window
     buffer
     `((body-function . ,#'select-window))))
   ((and (not (window-in-direction 'right))
         (not (window-in-direction 'left)))
    (display-buffer-in-direction
     buffer
     `((window-height . 0.4)
       (window-width . 0.4)
       (direction . right)
       (body-function . ,#'select-window))))
   (t
    (display-buffer-in-direction
     buffer
     `((window-height . 0.4)
       (window-width . 0.4)
       (direction . below)
       (body-function . ,#'select-window)))))) 

(setq popper-display-function #'joe/popper-display-func)
```

If there is a better way of doing this, feel free to suggest alterations to the approach. Any help would be appreciated. Thank you!

**Comment by JosephFerano** [comment]
Found something on stackoverflow to simplify the first condition;

```lisp
(defun joe/popper-display-func (buffer &optional _alist)
  (cond
   ((cl-find-if
     (lambda (window)
       (with-current-buffer (window-buffer window) popper-popup-status))
     (window-list))
    (display-buffer-reuse-window
     buffer
     `((body-function . ,#'select-window))))
   ((and (not (window-in-direction 'right))
         (not (window-in-direction 'left)))
    (display-buffer-in-direction
     buffer
     `((window-height . 0.4)
       (window-width . 0.4)
       (direction . right)
       (body-function . ,#'select-window))))
   (t
    (display-buffer-in-direction
     buffer
     `((window-height . 0.4)
       (window-width . 0.4)
       (direction . below)
       (body-function . ,#'select-window)))))) 
```

**Comment by karthink** [comment]
@JosephFerano Sorry for the delay.  The first condition doesn't work because `display-buffer-reuse-window` called with a buffer will only reuse a window that is already displaying that _specific_ buffer.  (This might sound useless -- but you can use it to change the parameters of the window that's displaying the buffer through the `alist` argument to `display-buffer`.)

The other change I'd make is to call the predicate `popper-popup-p` instead of checking `popper-popup-status`, which is an implementation detail and can break in the future. (It should really be `popper--popup-status`, but it's too late now.)

So instead of

``` emacs-lisp
(cond
 ((cl-find-if
     (lambda (window)
       (with-current-buffer (window-buffer window) popper-popup-status))
     (window-list))
    (display-buffer-reuse-window
     buffer
     `((body-function . ,#'select-window))))
 ;; Other cond clauses
 )
```

you could do something like this:

``` emacs-lisp
(cond
 ((when-let ((popup-buffer
              (cl-find-if
               #'popper-popup-p
               (mapcar #'window-buffer (window-list)))))
    (window--display-buffer
     buffer (get-buffer-window popup-buffer) 'reuse
     `((body-function . ,#'select-window)))))
 ;; Other cond clauses
 )
```

I haven't tested it, let me know if it works.
