### ISSUE TITLE
Popper makes grep result browsing start splitting windows

### ISSUE THREAD

**Issue by Lenbok** [karthink/popper#45]
Pre-popper, when I run `grep-find` with a single window (a), the results open in a new window (b), and after I enable `next-error-follow-minor-mode` with `C-c C-f` I can browse back and forth, with the window (a) updating as needed (including switching to a new file when required).

When I do this post-popper (I have `\\*grep\\*` in my `popper-reference-buffers`, BTW), as soon as I browse to a line corresponding to a new file, window (a) is split in two (with the new file being shown in the new split). Why is this, and how can I disable this, so that window (a) gets re-used like it used to?

My popper config:
```
(use-package popper
  :bind (("C-`"   . popper-toggle-latest)
         ("M-`"   . popper-cycle)
         ("C-M-`" . popper-toggle-type))
  :config
  (setq popper-reference-buffers
        '("\\*Messages\\*"
          "Output\\*$"
          "\\*Async Shell Command\\*"
          "\\*R:"
          help-mode
          compilation-mode
          magit-process-mode
          "\\*direnv\\*"
          "\\*Occur\\*"
          "\\*grep\\*"
          "\\*Embark Export"
          "\\*Embark Collect Live\\*"
          ))
  (setq popper-group-function #'popper-group-by-projectile)
  (popper-mode +1)
  (popper-echo-mode +1))
```

**Comment by karthink** [comment]
Hi @Lenbok,

This is an issue with how Emacs displays buffers in general, and there's not much Popper can do about it.

However, you can solve this problem by tweaking your general display-buffer settings. Can you try the following and let me know if it works?

```emacs-lisp
(setq display-buffer-base-action
      '((display-buffer-reuse-window
         display-buffer-reuse-mode-window)))
```

**Comment by Lenbok** [comment]
@karthink That helps as long as the file is of the same mode, but if there are file results that need different modes (e.g. python / txt / shell / xml) it'll still split (just the once though, although sometimes the sizes of the windows jump around).

**Comment by karthink** [comment]
@Lenbok Could you try

```emacs-lisp
(setq display-buffer-base-action
      '((display-buffer-reuse-window
         display-buffer-reuse-mode-window
         display-buffer-use-some-window)))
```

**Comment by Lenbok** [comment]
That seems to do the trick. (There is some weird effect occasionally where the split will change size when browsing across file types, but it doesn't seem to happen all the time.)

**Comment by karthink** [comment]
> (There is some weird effect occasionally where the split will change size when browsing across file types, but it doesn't seem to happen all the time.)

Not surre what could be causing that. If you want to customize buffer display further, I recommend Mickey Peterson's excellent article: https://www.masteringemacs.org/article/demystifying-emacs-window-manager

The elisp manual's section on `display-buffer` is also comprehensive, if a little dry. I'm closing this issue now, feel free to reopen if you run into issues due to the interaction between display-buffer stuff and Popper.
