### ISSUE TITLE
Helpful not getting POP label

### ISSUE THREAD

**Issue by bhepple** [karthink/popper#47]
A suggestion - you might want to put a more complete `popper-reference-buffers` in the README and doco. Also, the version for 'helpful' now (emacs-29) needs to be:

```
          "^\\*helpful .*\\*"
```

**Comment by karthink** [comment]
Thanks.  Do you have a suggestion for a "batteries-included" `popper-reference-buffers`?  Mine is rather idiosyncratic, since I do some matching by predicates, and don't use popular packages like Helpful.

**Comment by bhepple** [comment]
Not sure how comprehensive it is, but here's mine - idiosyncratic in my own way, no doubt:
```
;;;*** popper
(use-package popper
  :ensure t ; or :straight t
  :bind (("C-'"   . popper-toggle-latest)
         ("M-'"   . popper-cycle)
         ("C-M-'" . popper-toggle-type))
  :init
  (setq popper-reference-buffers
        '("\\*Messages\\*"
          "^\\*Warnings\\*"
          "Output\\*$"
          "\\*Async Shell Command\\*"
          "\\*Shell Command Output\\*"
          help-mode
          "^\\*helpful .*\\*"
          completions
          compilation-mode))
  (popper-mode +1)
  (popper-echo-mode +1))                ; For echo area hints
```

**Comment by karthink** [comment]
Does using `helpful-mode` instead of `"^\\*helpful .*\\*"` work?

**Comment by bhepple** [comment]
No - it does not work. The buffer-menu entry for helpful buffers looks like this:

```
 %* *helpful command: helpful-key*    1457 Helpful          command: helpful-key
```

**Comment by magthe** [comment]
> Does using `helpful-mode` instead of `"^\\*helpful .*\\*"` work?

It does seem to work for me, but them I'm running Emacs30 at the moment. Maybe worth trying it again with Emacs29?

**Comment by bhepple** [comment]
Yes - "helpful-mode" works now with emacs-29.1
