### ISSUE TITLE
`popper-cycle` in reverse direction?

### ISSUE THREAD

**Issue by gsingh93** [karthink/popper#48]
Is there a way to cycle popups in reverse? I was hoping `popper-cycle` had a direction argument that I could set to cycle the other way, but I didn't see anything like this. My use case is to bind `n` and `p` in `popper-mode-map` to cycle to the next or previous popup.

**Comment by gsingh93** [comment]
Oh, I realize now that `popper-mode-map` is not a mode map that's present only when a popup buffer is focused, it's always present when `popper-mode` is active. Which means my original use case won't work, but I still think cycling in the reverse direction could be useful regardless.

**Comment by phye** [comment]
Ohy, I happened to find that #49 is similar to this

**Comment by karthink** [comment]
Unfortunately it's written in a way that makes reverse cycling difficult. I've been meaning to rewrite that part of Popper, and will get to it at some point.

In the meantime, have you tried `popper-echo-mode`? This shows you a list of popups in the echo area and you can jump to the one you want directly with `M-1` through `M-9`.  You may need to enable this by setting `popper-echo-dispatch-actions`.

**Comment by phye** [comment]
I've tried this out and also the hidden `k/^` experimental feature in `popper-echo-mode`, but still feels that `n/p/k` pair to switch next/previous is more efficient than the current dispatch `M-[1-9]` binding.

Will watch on your update (and hope that will come soon :))

**Comment by karthink** [comment]
@gsingh93 and @phye: `popper-cycle` now cycles backwards when called with a negative prefix arg.  I also added a separate command (`popper-cycle-backwards`) that you can optionally use.

> I realize now that `popper-mode-map` is not a mode map that's present only when a popup buffer is focused, it's always present when `popper-mode` is active. Which means my original use case won't work, but I still think cycling in the reverse direction could be useful regardless.

If you want to "quick-cycle" backwards and forwards through popups, I suggest using a repeat-map (Emacs 28.1+ only):

``` emacs-lisp
(defvar popper-repeat-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "`") #'popper-cycle)
    (define-key map (kbd "~") #'popper-cycle-backwards)
    map))
  
(put 'popper-cycle-backwards 'repeat-map 'popper-repeat-map)
(put 'popper-cycle 'repeat-map 'popper-repeat-map)
(put 'popper-toggle-latest 'repeat-map 'popper-repeat-map)
```

When popper displays a popup, you can now cycle through popups forward and back with `\`` and `~`.  Replace with `n` and `p` if that's more convenient.

**Comment by karthink** [comment]
I'm closing this now, but feel free to reopen if something doesn't work as it should.

**Comment by phye** [comment]
Thanks!
