### ISSUE TITLE
`display-buffer` doesn't change current buffer

### ISSUE THREAD

**Issue by Elilif** [karthink/popper#54]
As shown in the function `popper-echo--dispatch-toggle`, `(display-buffer buf)` only displays `buf` in some window, without selecting it. That causes `popper-echo`, which uses `current-buffer`, to show duplicate popup items:

![2023-06-13_19-10](https://github.com/karthink/popper/assets/42063718/8ab05698-b450-4902-90dc-1c8d5d83f15e)

Should we add `(set-buffer buf)` or something else in `popper-echo--dispatch-toggle`?

**Comment by karthink** [comment]
> `(display-buffer buf)` only displays `buf` in some window, without selecting it.

What `display-buffer` does depends on the entry in `display-buffer-alist` that matches `buf`. Under the default settings, it will run `popper-select-popup-at-bottom`, which selects the popup. If `buf` corresponds to a `display-buffer-alist` entry that is not meant to be selected, then selecting it by force will mean not respecting `display-buffer-alist`, which we shouldn't do.

In any case, this is not the cause of the duplicate popup display bug, it has to do with how `popper-buried-popup-alist` is updated. I haven't been able to figure out the issue exactly -- if you can pinpoint it please let me know! My guess is it has to do with when exactly `window-configuration-change-hook` runs (or doesn't run), as that's when the popup lists are updated.
