### ISSUE TITLE
Loading problem from Elpa

### ISSUE THREAD

**Issue by grolongo** [karthink/popper#58]
Hi Karthink,  
Just to let you know I'm having issues when loading your package after fetching from Elpa with `use-package`.  
Somehow I get error messages that it cannot fetch from *Melpa*, despite the package already downloaded from *Elpa*.  
Then it cannot seem to load popper-echo saying `popper-echo-mode` is a function that doesn't exist.  
I reinstalled your package using the new `package-vc-selected-packages` variable in Emacs 29.1, and fetching directly from git it loads without problem.

**Comment by karthink** [comment]
It looks like there are multiple issues here, but I can't reproduce any of them.

If you have the time, could you check if these issues still persist for you when you try a direct fetch from ELPA?

**Comment by grolongo** [comment]
Hi karthink, it was apparently a problem with the Windows version of Emacs, as it was working fine on other platforms.  
I nuked my .emacs.d, reinstalled all packages and it worked fine even from ELPA 👍
