### ISSUE TITLE
Extract local functions from popper--set-reference-vars

### ISSUE THREAD

**Issue by roife** [karthink/popper#62]
This pull request is an extension of #57.

I want to implement distinct selection rules for various buffers with variables like `+popper-reference-buffers-no-select`. Currently, the buffer rules parsing and classification are handled within local functions in `popper--set-reference-vars`, which makes it hard to apply classification rules similar to those in popper-reference-buffers in my own functions.

I propose extracting `popper--classify-type` and `popper--insert-type` from `popper--set-reference-vars` to allow for independent use in custom functions. This modification will facilitate the classification of buffers within my own functions.

If this proposal aligns with the project's goals, I am glad to submit a pull request to implement these changes.

**Comment by winston-churchil** [comment]
Why not just do this? https://github.com/karthink/.emacs.d/blob/3f10a6153eb55cae77a6975b0ba979eedce0559e/init.el#L962

https://github.com/karthink/.emacs.d/blob/master/lisp/setup-windows.el#L80

```elisp
(defvar my/no-select-popup-buffers
  '("^\\*\\(?:.*?-\\)\\{0,1\\}e*shell[^z-a]*\\(?:\\*\\|<[[:digit:]]+>\\)$"
    "\\*.*REPL.*\\*"
    ...
```

```elisp
(setq popper-reference-buffers
   (append my/no-select-popup-buffers
          "^\\*Backtrace\\*"
             "^\\*evil-registers\\*"
             "^\\*Apropos"
             "^Calc:"
             "^\\
...
```

**Comment by roife** [comment]
> Why not just do this? https://github.com/karthink/.emacs.d/blob/3f10a6153eb55cae77a6975b0ba979eedce0559e/init.el#L962
> 
> https://github.com/karthink/.emacs.d/blob/master/lisp/setup-windows.el#L80
> 
> ```emacs-lisp
> (defvar my/no-select-popup-buffers
>   '("^\\*\\(?:.*?-\\)\\{0,1\\}e*shell[^z-a]*\\(?:\\*\\|<[[:digit:]]+>\\)$"
>     "\\*.*REPL.*\\*"
>     ...
> ```
> 
> ```emacs-lisp
> (setq popper-reference-buffers
>    (append my/no-select-popup-buffers
>           "^\\*Backtrace\\*"
>              "^\\*evil-registers\\*"
>              "^\\*Apropos"
>              "^Calc:"
>              "^\\
> ...
> ```

Thank you! However, I hope to implement this more flexibly, such as supporting popper's rule definitions. Currently, I'm achieving this with a hack:

```elisp
  ;; HACK: do not select window in `+popper-reference-buffer-no-select'
  (defvar +popper-unpacked-vars '(popper--reference-names
                                  popper--reference-modes
                                  popper--reference-predicates
                                  popper--suppressed-names
                                  popper--suppressed-modes
                                  popper--suppressed-predicates))
  (defvar +popper-unpacked-vars-no-select '())

  (dolist (var +popper-unpacked-vars)
    (let ((var-name (intern (concat "+" (symbol-name var) "-no-select"))))
      (eval
       `(progn
          (defvar ,var-name nil)
          (push ',var-name +popper-unpacked-vars-no-select)))))
  (setq +popper-unpacked-vars-no-select (reverse +popper-unpacked-vars-no-select))

  (cl-progv `(popper-reference-buffers ,@+popper-unpacked-vars)
      (list +popper-reference-buffer-no-select)
    (popper--set-reference-vars)
    (cl-loop for var in +popper-unpacked-vars
             for var-no-select in +popper-unpacked-vars-no-select
             do (eval `(setq ,var-no-select ',(symbol-value var)))))

  (defun +popper-smart-popup-at-bottom (buffer &optional alist)
    (let ((window (popper-display-popup-at-bottom buffer alist)))
      (unless (cl-progv +popper-unpacked-vars
                  (mapcar #'symbol-value +popper-unpacked-vars-no-select)
                (popper-popup-p buffer))
        (select-window window))))
  (setq popper-display-function #'+popper-smart-popup-at-bottom)
```

**Comment by wrycode** [comment]
Popper includes a basic way to display buffers as a courtesy but if you want different buffers to display differently, you should be using `display-buffer-alist`. If you do this, you can use whatever you code like to implement this feature, no modification of popper required.

I kind of wish Popper didn't even have the basic option to take over buffer display, and instead just included some helper code in the README that sets up something equivalent in 'display-buffer-alist', and maybe some helper variables and functions.I already came across several gotchas while trying to set this up myself (see #64).

**Comment by karthink** [comment]
@roife Using Popper for this is the wrong approach.  You can set `popper-display-control` to `nil` and set whatever rules you'd like (including which displayed windows should be selected) by customizing `display-buffer-alist`. You can find many examples of `display-buffer-alist` entries online if the manual is too annoying to read, or use the Shackle package to simplify this.

**Comment by karthink** [comment]
> I kind of wish Popper didn't even have the basic option to take over buffer display, and instead just included some helper code in the README that sets up something equivalent in 'display-buffer-alist'

While I share this sentiment, most Popper users don't know or care about `display-buffer-alist`, so without the convenience of `popper-display-control` this package would be unusable for most.

**Comment by roife** [comment]
Thanks for the clarification. I'll look into the `display-buffer-alist` first.
