### ISSUE TITLE
Support showing buffers from 'default' group

### ISSUE THREAD

**Issue by wrycode** [karthink/popper#63]
Here's my problem. I'm using `(setq popper-group-function #'popper-group-by-project)`. However, some buffers (like `*Messages*` and the default help window) don't 'belong' to a project, so I can't always  get to them without opening them directly. To open them with popper-toggle, I must first open a buffer that does not belong to a project. I looked into editing the project.el side of this but it isn't possible because a buffer can't simultaneously be in multiple projects. Do you have a recommended way to solve this? I could 
- add an option like `popper-group-include-default-group` and modify `popper--update-popups`, `popper--find-buried-popups`, and other functions to include buffers where `(project-current)` evaluates to `nil`
- Use a third party package like workgroups or tabspaces to create per-project help buffers? Not sure if this would work
- ???

**Comment by karthink** [comment]
> Do you have a recommended way to solve this?

I don't have a way of including buffers in the "default" group as members of every group.  A comprehensive solution will likely require changes across many Popper functions, as you indicate in option 1. This is tricky, I need to think about this more when I have time.

The messages buffer is universally accessible using `C-h e` by the way.

**Comment by wrycode** [comment]
Thanks. FWIW, after a few more days of using it I actually kind of like that those buffers are filtered out when I'm in a project now.

**Comment by karthink** [comment]
Okay. You can manually add them to a project (and thus to the popper group) by setting the default directory in that buffer. For example, you can run `(setq default-directory "/path/to/my/project")` in the Messages buffer.
