### ISSUE TITLE
popper-toggle-type does not work in buffers whose display is managed by display-buffer-alist by default

### ISSUE THREAD

**Issue by wrycode** [karthink/popper#64]
`popper-toggle-type` was very exciting to me when I first found out about popper because it means I retain the full power of Emacs' window management. It's a keybinding away if I need to dig deeper into a popup buffer and give it a persistent place in the main editing area while style cycling through other popups. However, unless I'm mistaken this only works when you have `(setq popper-display-control t)`?

To get the same behavior for other windows while using `display-buffer-alist` I had to add a check for a modded `popper-display-control-p` (renamed to `wrycode/is-popup`):

(config is a simplified version of your own)

```elisp
(defun wrycode/is-popup (buf &optional _act)
  "Predicate to test if buffer is a popup buffer.
This is intended to be used in `display-buffer-alist'."
  (let ((buffer (if (bufferp buf) buf (get-buffer buf))))
    (with-current-buffer buffer
      (or (memq popper-popup-status '(popup user-popup))
                (unless (eq popper-popup-status 'raised)
                  (popper-popup-p buffer))))))

(setq display-buffer-alist
      '(
	;; display search buffers in a dropdown in current window
	((lambda (buf act)
	   (and (member (buffer-mode buf) wrycode/search-modes-list)
		(wrycode/is-popup buf act)))
         (display-buffer-reuse-mode-window
          display-buffer-in-direction
          display-buffer-in-side-window)
         (side . top)
         (slot . 5)
         (window-height . (lambda (win) (fit-window-to-buffer win 20 10)))
         (direction . above)
         (body-function . select-window))

	;; display doc buffers on the right side for better reading
	((lambda (buf act) (and (member (buffer-mode buf) wrycode/docs-modes-list)
				(wrycode/is-popup buf act)))
         (display-buffer-reuse-mode-window
          display-buffer-in-direction
          display-buffer-in-side-window)
         (side . right)
         (slot . 5)
         (window-width . 90)
         (body-function . select-window))
	
	;; display all other popups using the default popper window	
	(wrycode/is-popup
	 (popper-select-popup-at-bottom))))
```

Perhaps this should be documented or somehow worked around?

**Comment by karthink** [comment]
> However, unless I'm mistaken this only works when you have `(setq popper-display-control t)`?

This isn't the case, it should work independent of the value of `popper-display-control`.  Can you give me a recipe to reproduce the bug with `popper-display-control` set to `nil`?

**Comment by wrycode** [comment]
You're right, `popper-toggle-type` works correctly when I have `popper-display-control` set to nil and use the `popper-display-control-p` predicate. However I may have come across a different bug while trying to reproduce this one?

```elisp
(setq straight-check-for-modifications '(find-when-checking check-on-save)
      ;; use-package uses straight automatically  (no need for :straight t option)
      use-package-by-default t
      straight-cache-autoloads t)
;; ↑these should be set before the straight bootstrap code

;; package management using straight.el; bootstrap code
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; install the use-package macro for convienant package loading
(straight-use-package 'use-package)

;; Shallow clone repositories by default (saves bandwidth and disk space)
(setq straight-vc-git-default-clone-dept 1)

(straight-use-package 'popper)

;; buffers that are designated as popups
(setq popper-reference-buffers
      '(Custom-mode
	ibuffer-mode
	compilation-mode
	edebug-eval-mode
	messages-buffer-mode))

(setq popper-display-control nil)	; buffer display is managed using display-buffer-alist rules
(setq popper-window-height 20)

;; For echo-area hints
(require 'popper-echo)
(popper-echo-mode +1)

(global-set-key (kbd "C-'") 'popper-toggle)
(global-set-key (kbd "M-'") 'popper-cycle)
(global-set-key (kbd "C-c '") 'popper-toggle-type)

(setq display-buffer-alist
      '(
	;; display popups using the default popper window
	(popper-display-control-p
	 (popper-select-popup-at-bottom))))

```

`popper-toggle`, immediately after loading this code, displays the `*Messages*` buffer on the right and does not select it. This is with `emacs -Q` and after deleting `~/.emacs.d`.

**Comment by karthink** [comment]
```elisp
(setq display-buffer-alist
      '(
	;; display popups using the default popper window
	(popper-display-control-p
	 (popper-select-popup-at-bottom))))
```

Why do you have this code in the config?

**Comment by wrycode** [comment]
Because I assumed that without this rule, popper would not manage the display of popup buffers (beyond calling `display-buffer`), because `popper-display-control` is `nil`. I don't want the popup buffers to be randomly displayed in the editing area. The default popper placement is actually good for most buffers. I have it as a fallthrough as you can see in my actual config:

```elisp
(setq display-buffer-alist
      '(
	;; display search buffers in a dropdown in current window
	((lambda (buffer-name action)
	   (and (member (buffer-mode buffer-name) wrycode/search-modes-list)
		(wrycode/is-popup buffer-name action))) ; We include this so popper-toggle-type works
         (display-buffer-reuse-mode-window
          display-buffer-in-direction
          display-buffer-in-side-window)
         (side . top)
         (slot . 5)
         (window-height . (lambda (win) (fit-window-to-buffer win 20 10)))
         (direction . above)
         (body-function . select-window))

	;; display doc buffers on the right side for better reading
	((lambda (buffer-name action)
	   (and (member (buffer-mode buffer-name) wrycode/docs-modes-list)
		(wrycode/is-popup buffer-name action)))
         (display-buffer-reuse-mode-window
          display-buffer-in-direction
          display-buffer-in-side-window)
         (side . right)
         (slot . 5)
         (window-width . 90)
         (body-function . select-window))
	
	display all other popups using the default popper window
	(wrycode/is-popup
	 (popper-select-popup-at-bottom))))
```

**Comment by wrycode** [comment]
Are `popper-display-control-p` and `popper-select-popup-at-bottom` only intended for internal popper use?

**Comment by karthink** [comment]
> immediately after loading this code, displays the *Messages* buffer on the right and does not select it.

I don't understand, did you display the messages buffer manually with `C-h e`?  Why would the above code display the messages buffer?

**Comment by karthink** [comment]
> Because I assumed that without this rule, popper would not manage the display of popup buffers (beyond calling `display-buffer`), because `popper-display-control` is `nil`. I don't want the popup buffers to be randomly displayed in the editing area. The default popper placement is actually good for most buffers. I have it as a fallthrough as you can see in my actual config:

Okay. It just seems to defeat the purpose of `popper-display-control` to set it to nil and then add this entry to `display-buffer-alist` anyway.

> Are `popper-display-control-p` and `popper-select-popup-at-bottom` only intended for internal popper use?

`popper-display-control-p` should be an internal function, but I named it wrong and haven't bothered to correct it.  `popper-select-popup-at-bottom` is not an internal function.

**Comment by karthink** [comment]
> I worded that confusingly, I meant calling popper-toggle immediately after loading that code displays the Messages buffer on the right and does not select it.

In that case the problem is probably that `messages-buffer-mode` is turned on by Emacs after displaying the buffer the first time. Try replacing it in `popper-reference-buffers` with `"\\*Messages\\*"`.

> Once I `popper-toggle` a popped-up docs buffer, for instance,...

I'm confused again. Did you mean `popper-toggle-type`?

**Comment by wrycode** [comment]
> I'm confused again. Did you mean popper-toggle-type?

Yes 🤦

**Comment by karthink** [comment]
>  I want to unstick it from the right side and allow it to be displayed in any window as a regular buffer. This is the intuitive behavior to me, so it could be worthwhile to expose a similar predicate for users in popper.

Have you looked at the documentation of `popper-display-control`?
