### ISSUE TITLE
Keeping Popup Selector Open

### ISSUE THREAD

**Issue by monibahmed** [karthink/popper#67]
HI, Popper is amazing, such a big boost to productivity, from a small utlity. Thank you!

Quick question though, when you switch to the popup buffer it brings up a menu showing the buffers available. Is there anyway to leave the open as long as you are in the popup buffer? 

For example, between a scratch buffer and a vterm buffer, if I write something into either on then and want to switch. I have to open/close the buffer. 

Thanks,

**Comment by karthink** [comment]
> HI, Popper is amazing, such a big boost to productivity, from a small utlity. Thank you!

Thanks for the kind words!

> Quick question though, when you switch to the popup buffer it brings up a menu showing the buffers available. Is there anyway to leave the open as long as you are in the popup buffer?

No, the little menu is only intended to let you see/switch to some other popup in case Popper toggled the "wrong" one.

But in your example, you can call `popper-cycle` instead of toggling, and that will either switch you from scratch to vterm, or it will activate the menu again and let you switch to vterm with `M-<num>`.  Have you tried this?

**Comment by monibahmed** [comment]
Yeah, the quick popup buffer switching is what makes the experience worthwhile (adding custom buffers to popup). 

Here is my popper setup? M-` does seem to cycle (unless i'm expecting something different). The M-<num> work wonderfully. 

```
#+begin_src emacs-lisp
  (use-package project
    :straight nil)
  (use-package popper
    :bind (("C-`"   . popper-toggle)
	   ("M-`"   . popper-cycle)
	   ("C-M-`" . popper-toggle-type))
    :init
    ;; have popper respect display-buffer-alist rules
    ;; (setq popper-display-control nil)
    ;; enable actions in echo area (k to kill buffer)
    ;; (setq popper-echo-dispatch-actions t)
    ;; how to group popups
    ;; (setq popper-display-function #'popper-select-popup-at-bottom)
    (setq popper-group-function #'popper-group-by-project)
    ;; which buffers should be considered popups
    (setq popper-window-height 0.33)
    (setq popper-reference-buffers
	'("\\*ChatGPT\\*"
	  "\\*scratch\\*"
	  "\\*vterm"
	    help-mode
	    compilation-mode))
    (popper-mode +1)
    (popper-echo-mode +1))                ; For echo area hints
#+end_src

```

**Comment by karthink** [comment]
> Here is my popper setup?

The configuration looks fine.  Did you have a specific question?

**Comment by monibahmed** [comment]
Yes, M-` seems to cycle through and then stop. The M-<num> options do not pop up again.

**Comment by monibahmed** [comment]
Closing, Popper working as expected.
