### ISSUE TITLE
Problem with pop buffers that are opened outside of a popper window

### ISSUE THREAD

**Issue by Doodler8888** [karthink/popper#70]
I frequently encounter a situation where a popper buffer is opened outside of the designated popper window (in a normal window). When I attempt to open a popper window using popper-toggle, it moves all popper buffers within the current frame that are outside the popper window back into it.

I would like to achieve a behavior where opening a popper window does not automatically move any other popper buffers within the current frame back into the popper window. But i have absolutely no idea how to do that.

**Comment by Doodler8888** [comment]
Just using 'popper-toggle-type' to remove the popper-mode from the buffer and then use 'popper-toggle' to open a popper window is problematic, because using 'popper-toggle-type' on popper buffers that are outside of a popper window will move these buffers to other windows, which breaks my layout.

I made a separate function for removing the pop status from active buffers. But expanding it further doesn't lead anywhere.


  ```
(defun my-buffer-is-popper-popup-p ()
    "Check if the current buffer is considered a Popper popup."
    (and (boundp 'popper-popup-status)
        (buffer-local-value 'popper-popup-status (current-buffer))))

  (defun my-check-current-buffer-popper-status ()
    "Print whether the current buffer is a Popper popup."
    (interactive)
    (if (my-buffer-is-popper-popup-p)
        (message "Current buffer IS a Popper popup.")
      (message "Current buffer is NOT a Popper popup.")))

  (defun my-popper-toggle-type ()
    "Pin the current buffer to its current window, then toggle its popup status."
    (interactive)
    (let ((buffer (current-buffer))
          (window (selected-window)))
      ;; Define a temporary rule to pin the buffer to its current window
      (setq shackle-rules
            (append shackle-rules
                    `((,(buffer-name buffer) :same t))))
      ;; Update the shackle mode
      (shackle-mode 1)
      ;; Toggle the popup status
      (popper-toggle-type)
      ;; Remove the temporary rule
      (setq shackle-rules
            (cl-remove-if (lambda (rule) (equal (car rule) (buffer-name buffer)))
                          shackle-rules))
      ;; Update the shackle mode
      (shackle-mode 1)
      ;; Ensure the buffer stays in the current window
      (set-window-buffer window buffer)))

  (defun my-remove-popper-status-from-frame-buffers ()
    "Remove popper status from all buffers with popper mode in the current frame."
    (interactive)
    (let ((frame-buffers (buffer-list (selected-frame)))
          (current-buffer (current-buffer))
          (current-window (selected-window)))
      (unwind-protect
          (dolist (buffer frame-buffers)
            (when (and (buffer-live-p buffer)
                      (get-buffer-window buffer))
              (with-selected-window (get-buffer-window buffer)
                (with-current-buffer buffer
                  (when (my-buffer-is-popper-popup-p)
                    (my-popper-toggle-type))))))
        ;; Ensure we return to the original buffer and window
        (when (window-live-p current-window)
          (select-window current-window))
        (when (buffer-live-p current-buffer)
          (set-buffer current-buffer)))))
```

**Comment by karthink** [comment]
> I would like to achieve a behavior where opening a popper window does not automatically move any other popper buffers within the current frame back into the popper window. But i have absolutely no idea how to do that.

This isn't possible right now, as Popper assumes that any visible popup buffers are active popups.  There is no concept of a "popper window".

Here's something you can do: when you have a popup buffer showing in a "regular" window, call `popper-toggle` with a prefix arg.  This should leave the buffer alone and pop up the next buffer.  From this point you can use Popper as usual.

> Just using 'popper-toggle-type' to remove the popper-mode from the buffer and then use 'popper-toggle' to open a popper window is problematic, because using 'popper-toggle-type' on popper buffers that are outside of a popper window will move these buffers to other windows, which breaks my layout.

Undo your customization, then try this:

```elisp
(define-advice popper-raise-popup (:override (&optional buffer) switch-and-stay)
  (when-let ((buf (get-buffer (or buffer (current-buffer)))))
    (with-current-buffer buf
      (if (popper-popup-p buf)
          (setq popper-popup-status 'raised)
        (setq popper-popup-status nil))
      (setq mode-line-format (default-value 'mode-line-format)))))
```

Now use `popper-toggle-type` as usual.
